name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    # manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Add username and email
        run: |
          git config --global user.name Amarpreet Singh
          git config --global user.email solamarpreet@gmail.com

      - name: Get Theme
        run: git submodule update --init --recursive

      - name: Update Theme
        run: git submodule update --remote --merge

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --gc --verbose --minify
